########################################
########################################
###                                  ###
###      Discord Economy Bridge      ###
###   Made by Pliexe/DiamondZombie   ###
###                                  ###
########################################

# DO NOT SHARE THE BOT TOKEN WITH ANYONE! If you are using DiscordSRV you can ignore this field!
TOKEN: BOT_TOKEN

# Independent usage of plugin alongside with DiscordSRV
# This means that DiscordEconomyBridge will ignore DiscordSRV and work Standalone
independent: false

# This only works in "independent" mode. Use this to enable the usage of DiscordSRV linking system inside "independent" mode
useDiscordSRVLinking: false


# Status
# Type of status, can be: (Playing, playing), (Watching, watching), (Listening, listening), (Streaming, streaming)
# You can remove statusType and statusMessage if you want!
statusType: Playing
statusMessage: "!help"
# Use this when using streaming status type to link your stream (not required when using streaming type)
# statusStreamURL: "twitch.tv"

# Bot prefix
PREFIX: "!"

# Currency
Currency: "$"
CurrencyLeftSide: false

# Max users to show in leaderboard
leaderboardSlots: 10

# Ignore permission check for discord administrator permission
ignorePermissionsForAdministrators: false

# Disable viewing balance of other users in !balance command
disableViewingOfOtherUsers: false

discordModerators:
#  - "477622334182785025"
#  - ROLEID2

slashCommandServers:
#  - "477617680631726092"

## DiscordSRV warn
# If set to true the unsupported commands that only work with DiscordSRV will not reply
noDiscordSRVwarn: false

# Min_Max wager/bet
maxBet: 100000000000000000
minBet: 50

## Aliases

aliases:
  blackjack:
    - bj
  coinflip:
    - cf
  leaderboard:
    - lb
    - top
  balance:
    - bal
  removemoney:
    - remmoney
    - remoney
  rockpaperscissors:
    - rps


## Command customizations


# Disabled commands
#disabledCommands:
#  - help

##############################
### Commands customization ###
##############################

# Command customization has been moved to discord_messages.yml

#######################
### Custom commands ###
#######################

##############################
### Available placeholders ###
###
### {messageContent} - The whole message's content
### {messageContentWithoutCommand} - The message's content without the command part
### {username} - Player's username
### {PlayerStatus} - Tell if the player is online. Example: Player is Online
### {playerStatus} - Tell if the player is online. Example: Player is online
### {joinDate} - Player's join date
###
###                        ###
##############################


customCommands:
#  say:
#    content: "{messageContentWithoutCommand}"
  info:
    inputs:
      - "OnlinePlayer"
    aliases:
      - user
    embed:
      color: 0x3242a8
#      author:
#        name: "John"
#        icon_url: "https://yes"
#        url: "https://visitme:
#      image: "https://yes"
#      thumnail: "https://yes"
#      icon_url: "https://yes"
#      title: "Title of this embed"
#      footer:
#        text: "A footer example"
#        icon_url: "any icon url can be placed here"
      fields:
        "Username":
          text: "{username}"
          inline: true
        "Status":
          text: "{PlayerStatus}"
          inline: true
        "Join date":
          text: "{joinDate}"
          inline: true