main: me.pliexe.discordeconomybridge.DiscordEconomyBridge
name: DiscordEconomyBridge
version: 1.4
description: A plugin for server economy bridge with discord
load: POSTWORLD
author: pliexe

depend: [Vault]

loadbefore: [floodgate-bukkit]

#commands:
#  example:
#    description: aaaa