main: me.pliexe.discordeconomybridge.DiscordEconomyBridge
name: DiscordEconomyBridge
version: 2.0
description: A plugin for server economy bridge with discord
load: POSTWORLD
author: pliexe

depend: [Vault]
softdepend: [PlaceholderAPI, DiscordSRV]

loadbefore: [floodgate-bukkit]

#commands:
#  example:
#    description: aaaa